server.port: 8080

spring:
  datasource:
    hikari:
      sqlite:
        jdbc-url: jdbc:sqlite:database/sqlite.db
        username:
        password:
        driver-class-name: org.sqlite.JDBC
      mysql:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/db0314?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
